spring:
  application:
    name: logistics
  datasource:
    url: jdbc:mariadb://localhost:3307/groceryshop
    username: grocery
    password: grocery
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
